nelmio_api_doc:
    documentation:
        info:
            title: ' %env(PROJECT_NAME)% documentation'
            version: '1.0.0'
#            description: 'API v2%project_version%''
#        securityDefinitions:
#            Bearer:
#                type: apiKey
#                description: 'Value: Bearer {jwt}'
#                name: Authorization
#                in: header
#        security:
#            - Bearer: []  
    models: { use_jms: false }
    areas:
        api:
            path_patterns:
                - ^/api
        default:
            path_patterns:
                - ^/
            
            
